/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment2;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class BookSortingApplication extends javax.swing.JFrame {
    
    BookSortingApplicationMethods bsam = new BookSortingApplicationMethods();
    static ArrayList <Crime> crimeList = new ArrayList <Crime>(1);
    static ArrayList <Drama> dramaList = new ArrayList <Drama>(1);
    static DefaultListModel listModel = new DefaultListModel();
    
    public BookSortingApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        load_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookJList = new javax.swing.JList<>();
        add_btn = new javax.swing.JButton();
        viewPenalty_btn = new javax.swing.JButton();
        quit_btn = new javax.swing.JButton();
        searchByID_btn = new javax.swing.JButton();
        searchByAuthor_btn = new javax.swing.JButton();
        seeFinesBorrower_btn = new javax.swing.JButton();
        sortByID_btn = new javax.swing.JButton();
        sortByMostPopular_btn = new javax.swing.JButton();
        sortByOverTenDays_btn = new javax.swing.JButton();
        sortByMaxRev_btn = new javax.swing.JButton();
        viewSpecOverAllFine_btn = new javax.swing.JButton();
        viewOverAllFine_btn = new javax.swing.JButton();
        viewTopThreeEarners_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        load_btn.setText("Load");
        load_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load_btnActionPerformed(evt);
            }
        });

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(bookJList);

        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        viewPenalty_btn.setText("View Penalty");
        viewPenalty_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPenalty_btnActionPerformed(evt);
            }
        });

        quit_btn.setText("Quit");
        quit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_btnActionPerformed(evt);
            }
        });

        searchByID_btn.setText("Search by ID");
        searchByID_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByID_btnActionPerformed(evt);
            }
        });

        searchByAuthor_btn.setText("Search by Author");
        searchByAuthor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByAuthor_btnActionPerformed(evt);
            }
        });

        seeFinesBorrower_btn.setText("See fines from Borrower");
        seeFinesBorrower_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeFinesBorrower_btnActionPerformed(evt);
            }
        });

        sortByID_btn.setText("Sort by ID");
        sortByID_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByID_btnActionPerformed(evt);
            }
        });

        sortByMostPopular_btn.setText("Sort by Most Popular");
        sortByMostPopular_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByMostPopular_btnActionPerformed(evt);
            }
        });

        sortByOverTenDays_btn.setText("Sort by Books Over 10 days");
        sortByOverTenDays_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByOverTenDays_btnActionPerformed(evt);
            }
        });

        sortByMaxRev_btn.setText("Sort by Max Revenue");
        sortByMaxRev_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByMaxRev_btnActionPerformed(evt);
            }
        });

        viewSpecOverAllFine_btn.setText("View Specific Overall Fine");
        viewSpecOverAllFine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSpecOverAllFine_btnActionPerformed(evt);
            }
        });

        viewOverAllFine_btn.setText("View Overall Fine");
        viewOverAllFine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOverAllFine_btnActionPerformed(evt);
            }
        });

        viewTopThreeEarners_btn.setText("View Top Three Earners");
        viewTopThreeEarners_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTopThreeEarners_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(save_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(load_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(searchByID_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchByAuthor_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seeFinesBorrower_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPenalty_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortByID_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortByMostPopular_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortByOverTenDays_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(sortByMaxRev_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewSpecOverAllFine_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewOverAllFine_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewTopThreeEarners_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quit_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_btn)
                            .addComponent(load_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewTopThreeEarners_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewOverAllFine_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSpecOverAllFine_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortByMaxRev_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortByOverTenDays_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortByMostPopular_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortByID_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seeFinesBorrower_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByAuthor_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchByID_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewPenalty_btn))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Opens a window to allow the user to enter a file name without the .txt extension, calls the load file method
     */
    private void load_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load_btnActionPerformed
        //open pop up window telling the user to enter a txt file name
        //JOptionPane.showConfirmDialog(null, "", "Enter a txt name in the java directory", JOptionPane.OK_OPTION);
        try
        {
            listModel.clear();
            if(bsam.loadFile(JOptionPane.showInputDialog(null, "Enter a text file name WITHOUT the extension")+".txt"))
            {
                bsam.updateListbox();
                bookJList.setModel(listModel);
            }
        }
        catch(NullPointerException e)
        {
            System.out.println("There was a null pointer exception error, that being: "+e.getMessage());
            //JOptionPane.showConfirmDialog(null, "There was a null pointer exception: "+e.getMessage(), "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_load_btnActionPerformed
    
    /**
     * Calls the add book and update list box method 
     */
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        bsam.addBook();
        bsam.updateListbox();
        bookJList.setModel(listModel);//step 1
    }//GEN-LAST:event_add_btnActionPerformed
    
    /**
     * Opens a window showing the total penalty a book has
     */
    private void viewPenalty_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPenalty_btnActionPerformed
        int x = bsam.viewPenalty(Integer.parseInt(String.valueOf(bookJList.getSelectedIndex()).trim()));
        if(x != 0)
        {
            JOptionPane.showConfirmDialog(null, "There is a $"+x+" penalty for this book", "Penalty", JOptionPane.PLAIN_MESSAGE);
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "There is a no penalty for this book", "Penalty", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_viewPenalty_btnActionPerformed
    
    /**
     * calls the save file method
     */
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        bsam.saveFile();
    }//GEN-LAST:event_save_btnActionPerformed
    
    /**
     * calls the quit method
     */
    private void quit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_btnActionPerformed
        bsam.quit();
    }//GEN-LAST:event_quit_btnActionPerformed
    
    /**
     * Opens a window for the user to enter an ID and calls the search id method
     */
    private void searchByID_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByID_btnActionPerformed
        try
        {
            bsam.searchByID(JOptionPane.showInputDialog(null, "Enter the ID you would like to search with"));
        }
        catch(NullPointerException e)
        {
            System.out.println("There was a null pointer exception error, that being: "+e.getMessage());
            //JOptionPane.showConfirmDialog(null, "There was a null pointer exception: "+e.getMessage(), "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_searchByID_btnActionPerformed
    
    /**
     * Opens a window for the user to enter an author and calls the search author method
     */
    private void searchByAuthor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByAuthor_btnActionPerformed
        try
        {
            bsam.searchByAuthor(JOptionPane.showInputDialog(null, "Enter the Author you would like to search by"));
        }
        catch(NullPointerException e)
        {
            System.out.println("There was a null pointer exception error, that being: "+e.getMessage());
            //JOptionPane.showConfirmDialog(null, "There was a null pointer exception: "+e.getMessage(), "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_searchByAuthor_btnActionPerformed
    
    /**
     * Opens a window for the user to enter an the name of a borrower and calls the search id method
     */
    private void seeFinesBorrower_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeFinesBorrower_btnActionPerformed
        bsam.seeFinesFromBorrower(JOptionPane.showInputDialog(null, "Enter the Borrower you would like to see the fines for"));
    }//GEN-LAST:event_seeFinesBorrower_btnActionPerformed
    
    /**
     * calls the sortId method and sets the listModel
     */
    private void sortByID_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByID_btnActionPerformed
        bsam.sortByID();
        bookJList.setModel(listModel);
    }//GEN-LAST:event_sortByID_btnActionPerformed
    
    /**
     * calls the sortByMostPopular method and sets the listModel
     */
    private void sortByMostPopular_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByMostPopular_btnActionPerformed
        bsam.sortByMostPopular();
        bookJList.setModel(listModel);
    }//GEN-LAST:event_sortByMostPopular_btnActionPerformed
    
    /**
     * calls the sortByOverTenDays method and sets the listModel
     */
    private void sortByOverTenDays_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByOverTenDays_btnActionPerformed
        bsam.sortBy10Days();
        bookJList.setModel(listModel);
    }//GEN-LAST:event_sortByOverTenDays_btnActionPerformed
    
    /**
     * calls the max revenue method and sets the listModel
     */
    private void sortByMaxRev_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByMaxRev_btnActionPerformed
        bsam.sortByMaxRev();
        bookJList.setModel(listModel);
    }//GEN-LAST:event_sortByMaxRev_btnActionPerformed
    
    
    /**
     * calls the overAllSpecificFine method and displays it in a pop up text box
     */
    private void viewSpecOverAllFine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSpecOverAllFine_btnActionPerformed
        JOptionPane.showConfirmDialog(null, "The total fine for the selected book type is: $"+bsam.overAllSpecificFine(), "Spec. total fine", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_viewSpecOverAllFine_btnActionPerformed
    
    /**
     * calls the overAllFine method and displays it in a pop up text box
     */
    private void viewOverAllFine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOverAllFine_btnActionPerformed
        //bsam.overAllFine();
        JOptionPane.showConfirmDialog(null, "The total fine for the selected book type is: $"+bsam.overAllFine(), "Spec. total fine", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_viewOverAllFine_btnActionPerformed
    
    /**
     * calls the top three earners method 
     */
    private void viewTopThreeEarners_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTopThreeEarners_btnActionPerformed
        bsam.topThreeEarners();
    }//GEN-LAST:event_viewTopThreeEarners_btnActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSortingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSortingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSortingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSortingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSortingApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JList<String> bookJList;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton load_btn;
    private javax.swing.JButton quit_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton searchByAuthor_btn;
    private javax.swing.JButton searchByID_btn;
    private javax.swing.JButton seeFinesBorrower_btn;
    private javax.swing.JButton sortByID_btn;
    private javax.swing.JButton sortByMaxRev_btn;
    private javax.swing.JButton sortByMostPopular_btn;
    private javax.swing.JButton sortByOverTenDays_btn;
    private javax.swing.JButton viewOverAllFine_btn;
    private javax.swing.JButton viewPenalty_btn;
    private javax.swing.JButton viewSpecOverAllFine_btn;
    private javax.swing.JButton viewTopThreeEarners_btn;
    // End of variables declaration//GEN-END:variables
}
